apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: must-gather-sandboxed-containers-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: must-gather-sandboxed-containers-operator
    app.kubernetes.io/part-of: sandboxed-containers-operator
  name: must-gather-sandboxed-conq5xd
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: must-gather-sandboxed-containers-operator
    weight: 100
status: {}
