apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: toolspackagingkata-monitor-kata-containers
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: toolspackagingkata-monitor-kata-containers
    app.kubernetes.io/part-of: sandboxed-containers-operator
  name: toolspackagingkata-monitor-kata-containers
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: toolspackagingkata-monitor-kata-containers
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: toolspackagingkata-monitor-kata-containers
    spec:
      containers:
      - image: image
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
