apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: toolspackagingkata-monitor-kata-containers
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: toolspackagingkata-monitor-kata-containers
    app.kubernetes.io/part-of: sandboxed-containers-operator
  name: toolspackagingkata-monitor-kata-containers
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: toolspackagingkata-monitor-kata-containers
status:
  loadBalancer: {}
