apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: webhook-cloud-api-adaptor
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: webhook-cloud-api-adaptor
    app.kubernetes.io/part-of: sandboxed-containers-operator
  name: webhook-cloud-api-adaptor
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: webhook-cloud-api-adaptor
status:
  loadBalancer: {}
