apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: must-gather-sandboxed-containers-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: must-gather-sandboxed-containers-operator
    app.kubernetes.io/part-of: sandboxed-containers-operator
  name: must-gather-sandboxed-containers-operator
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: must-gather-sandboxed-containers-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: must-gather-sandboxed-containers-operator
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-dbox-containers-tenant/sandboxed-containers-operator/must-gather-sandboxed-containers-operator@sha256:8fb70288b432fe7fb7e2f01c6484d37f7130bdc3b2050574b8cc0eabc0491fd9
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
